### ISSUE TITLE
Update `CONTRIBUTING.md` file with how to contribute steps.

### ISSUE THREAD

**Issue by soyo-kaze** [soyo-kaze/Next-blog-site#4]

**Comment by Abhirv08** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by soyo-kaze** [comment]
Happy Hacktober @Abhirv08 ..
Things I want in this plus whatever you can add.
- Contributors should create a new branch with their contribution also add the issue in that PR.
- Try to create Issue first.

**Comment by Abhirv08** [comment]
okay sure.
